### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by thomasfire** [thomasfire/atomiki#1]
- [x] Proper notifications on errors, warnings and competitor moves
- [x] Tutorial page
- [x] Login on refresh page, to restore connection
- [ ] Test on mobiles with unstable internet
- [x] Complete readme with build instructions
- [x] Minor fixes if needed
- [x] Wrap into docker/compose
- [x] Publish to some webhosting
- [x] Add QR code
- [x] Copyrights
- [ ] Donations
- [ ] Bettings on TVM?
- [x] UTF-8
- [x] Cachebust
- [ ] Bot-competitor for those who cannot find human ones
- [x] Highlight the current movement results
- [x] Placeholder while the main script is loading
- [ ] Telemetry and privacy policy
- [ ] Support line
- [x] Optimize bundle size
- [ ] Landscape layout
- [x] Get rid of coordinates conversion in API
- [ ] Modular rules?
- [ ] Paid game modes?
- [x] remove join from tutorial
- [ ] accessibility
- [ ] Telegram mini app integration
- [ ] Color palletes
- [ ] Matchmaking and betting
- [ ] Animated guides and tutorials - should be shown only once by client-side cookies
